// <auto-generated />
using English_QA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace English_QA.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251001122509_removeColumn")]
    partial class removeColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("English_QA.Models.DatabaseModels.AnswerTypes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnswerTypes");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.QA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AnswerTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MultipleAnswer01")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MultipleAnswer02")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MultipleAnswer03")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MultipleAnswer04")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("questionCategoryID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnswerTypeID");

                    b.HasIndex("questionCategoryID");

                    b.ToTable("QA");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.QuestionCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("questionCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuestionCategory");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.TestResults", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CountQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Results")
                        .HasColumnType("REAL");

                    b.Property<long>("TestPerAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TestResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserTestID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserTestID");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UsersTypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsersTypeID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.UsersType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsersType");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.UserTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AnswerTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MultipleAnswer01")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MultipleAnswer02")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MultipleAnswer03")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MultipleAnswer04")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TestCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("questionCategoryID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnswerTypeID");

                    b.HasIndex("UserID");

                    b.HasIndex("questionCategoryID");

                    b.ToTable("UserTest");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.QA", b =>
                {
                    b.HasOne("English_QA.Models.DatabaseModels.AnswerTypes", "answerType")
                        .WithMany()
                        .HasForeignKey("AnswerTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("English_QA.Models.DatabaseModels.QuestionCategory", "questionCategory")
                        .WithMany()
                        .HasForeignKey("questionCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("answerType");

                    b.Navigation("questionCategory");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.TestResults", b =>
                {
                    b.HasOne("English_QA.Models.DatabaseModels.UserTest", "UserTest")
                        .WithMany()
                        .HasForeignKey("UserTestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTest");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.Users", b =>
                {
                    b.HasOne("English_QA.Models.DatabaseModels.UsersType", "usersType")
                        .WithMany()
                        .HasForeignKey("UsersTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usersType");
                });

            modelBuilder.Entity("English_QA.Models.DatabaseModels.UserTest", b =>
                {
                    b.HasOne("English_QA.Models.DatabaseModels.AnswerTypes", "answerType")
                        .WithMany()
                        .HasForeignKey("AnswerTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("English_QA.Models.DatabaseModels.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("English_QA.Models.DatabaseModels.QuestionCategory", "questionCategory")
                        .WithMany()
                        .HasForeignKey("questionCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("answerType");

                    b.Navigation("questionCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
